LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:= qrngd.c
LOCAL_SHARED_LIBRARIES := libc libcutils
LOCAL_CFLAGS := -DANDROID_CHANGES
LOCAL_MODULE = qrngd
LOCAL_MODULE_TAGS := optional
include $(BUILD_EXECUTABLE)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:= qrngp.c
LOCAL_SHARED_LIBRARIES := libc libcutils
LOCAL_CFLAGS := -DANDROID_CHANGES
LOCAL_C_INCLUDES := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr/include
LOCAL_ADDITIONAL_DEPENDENCIES := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ/usr
LOCAL_MODULE = qrngp
LOCAL_MODULE_TAGS := optional
include $(BUILD_EXECUTABLE)
